
Data_Pipeline:
  # Directory
  TRAIN_DIR : 'C:\DogBreed\splited_image\train'
  VALID_DIR : 'C:\DogBreed\splited_image\val'
  TEST_DIR : 'C:\DogBreed\splited_image\test'
  # Training mode
  MODE : 'TRAIN' # [VALID, TEST]
  # Dataset
  IMG_SIZE : 224
  TRANS_MEAN : [0.485, 0.456, 0.406]
  TRANS_STD : [0.229, 0.224, 0.225]
  # Dataloader
  BATCH_SIZE : 16


MODEL:
  # hidden layers
  HIDDENS : [512, 256, 64]
  # Drop out 
  DROPOUT : 0.1
  # number of outputs
  OUTPUTS : 120
  # pretrained model [resnet50,
  PRETRAINED : 'resnet50'
  
TRAINING:
  # Training details
  EPOCH : 50
  LR : 0.001
  DEVICE : 'cuda'
  
  # Settings
  MODE : 'train'

  # Directory
  TRAIN_DIR : 'C:\DogBreed\train_dir'
  MODEL_DIR : 'C:\DogBreed\model'





