
Data_Pipeline:

  TRAIN_DIR :
  TEST_DIR :

  MODE : 'TRAIN' # Valid / Test

  # Dataset
  IMG_SIZE : 224
  TRANS_MEAN : [0.485, 0.456, 0.406]
  TRANS_STD : [0.229, 0.224, 0.225]

  # Dataloader
  BATCH_SIZE : 16


MODEL:

  # hidden layers
  HIDDENS : [512, 256, 64]

  # number of outputs
  OUTPUTS :

  # pretrained model [resnet50,
  PRETRAINED : 'resnet50'





